//! Macros for registering editor primitives at compile time.
//!
//! These macros generate static entries in [`linkme`] distributed slices,
//! enabling zero-cost registration of actions, keybindings, motions, hooks,
//! and other extensible editor components.
//!
//! # Primary Macros
//!
//! - [`action!`] - Register actions with optional keybindings and handlers
//! - [`motion!`] - Cursor/selection movement primitives
//! - `hook!` has moved to `evildoer-registry-hooks`
//! - `command!` has moved to `evildoer-registry-commands`
//! - `panel!` has moved to `evildoer-registry-panels`
//!
//! # Secondary Macros
//!
//! - [`option!`] - Configuration options
//! - [`text_object!`] - Text object selection (`iw`, `a"`, etc.) - now in evildoer-registry
//! - [`statusline_segment!`] - Statusline segment definitions
//!
//! # Event Definitions
//!
//! Hook events and their extractors are generated by `evildoer_macro::define_events!`
//! in `hooks.rs`. This provides a single source of truth for event types.
//!
//! Note: Language definitions are loaded at runtime from `languages.kdl`.

// Internal modules containing macro definitions
mod actions;
mod helpers;
mod registry;

// Re-export all macros at module level
// Note: __hook_extract and __async_hook_extract are generated by define_events! proc macro
// Note: text_object macros (text_object!, symmetric_text_object!, bracket_pair_object!)
// are now in evildoer-registry and re-exported at crate root
pub use crate::{
	__opt, __opt_slice, action, bracket_pair_object, motion, option, result_handler,
	statusline_segment, symmetric_text_object, text_object,
};
