//! Identifier types for editor entities.

/// Unique identifier for a view (buffer instance).
///
/// Each view represents an independent editing context with its own cursor,
/// selection, and scroll position. Multiple views can share the same underlying
/// document (for split views), but each has a unique `ViewId`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ViewId(pub u64);

impl ViewId {
	/// Identifier for the default scratch buffer.
	pub const SCRATCH: ViewId = ViewId(0);

	/// Creates a new view ID for a text buffer.
	///
	/// This is a convenience constructor that matches the hook API.
	pub const fn text(id: u64) -> Self {
		Self(id)
	}
}

/// String-based identifier for motion primitives.
///
/// Motion IDs allow actions to reference motions by name without depending
/// on the motions crate directly. The executor resolves these IDs to actual
/// motion handlers at runtime.
///
/// Format: `"crate-name::motion_name"` (e.g. `"xeno-registry-motions::left"`)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct MotionId(pub &'static str);

impl MotionId {
	/// Returns the string representation of this motion ID.
	#[inline]
	pub const fn as_str(self) -> &'static str {
		self.0
	}
}

/// Well-known motion IDs for use in action definitions.
///
/// These constants mirror the motion IDs generated by the `motion!` macro
/// in the `xeno-registry-motions` crate.
pub mod motion_ids {
	use super::MotionId;

	// Horizontal motions
	pub const LEFT: MotionId = MotionId("xeno-registry-motions::left");
	pub const RIGHT: MotionId = MotionId("xeno-registry-motions::right");

	// Vertical motions
	pub const UP: MotionId = MotionId("xeno-registry-motions::up");
	pub const DOWN: MotionId = MotionId("xeno-registry-motions::down");

	// Line motions
	pub const LINE_START: MotionId = MotionId("xeno-registry-motions::line_start");
	pub const LINE_END: MotionId = MotionId("xeno-registry-motions::line_end");
	pub const FIRST_NONWHITESPACE: MotionId =
		MotionId("xeno-registry-motions::first_nonwhitespace");

	// Document motions
	pub const DOCUMENT_START: MotionId = MotionId("xeno-registry-motions::document_start");
	pub const DOCUMENT_END: MotionId = MotionId("xeno-registry-motions::document_end");

	// Word motions
	pub const NEXT_WORD_START: MotionId = MotionId("xeno-registry-motions::next_word_start");
	pub const PREV_WORD_START: MotionId = MotionId("xeno-registry-motions::prev_word_start");
	pub const NEXT_WORD_END: MotionId = MotionId("xeno-registry-motions::next_word_end");
	pub const NEXT_LONG_WORD_START: MotionId =
		MotionId("xeno-registry-motions::next_long_word_start");
	pub const PREV_LONG_WORD_START: MotionId =
		MotionId("xeno-registry-motions::prev_long_word_start");
	pub const NEXT_LONG_WORD_END: MotionId = MotionId("xeno-registry-motions::next_long_word_end");

	// Paragraph motions
	pub const NEXT_PARAGRAPH: MotionId = MotionId("xeno-registry-motions::next_paragraph");
	pub const PREV_PARAGRAPH: MotionId = MotionId("xeno-registry-motions::prev_paragraph");

	// Diff motions
	pub const NEXT_HUNK: MotionId = MotionId("xeno-registry-motions::next_hunk");
	pub const PREV_HUNK: MotionId = MotionId("xeno-registry-motions::prev_hunk");
}
