//! Blob embedding and deserialization for registry metadata.
//!
//! Each domain has an embedded precompiled blob and a corresponding loader
//! function. The blobs are generated by `build.rs` from KDL source files.

use super::types::{
	ActionsBlob, CommandsBlob, GuttersBlob, HooksBlob, MotionsBlob, NotificationsBlob, OptionsBlob,
	StatuslineBlob, TextObjectsBlob, ThemesBlob,
};

mod blobs;
mod internal;

use blobs::*;
use internal::*;

/// Loads and deserializes the embedded action metadata blob.
pub fn load_action_metadata() -> ActionsBlob {
	load_blob(ACTIONS_BLOB, "actions")
}

/// Loads and deserializes the embedded command metadata blob.
pub fn load_command_metadata() -> CommandsBlob {
	load_blob(COMMANDS_BLOB, "commands")
}

/// Loads and deserializes the embedded motion metadata blob.
pub fn load_motion_metadata() -> MotionsBlob {
	load_blob(MOTIONS_BLOB, "motions")
}

/// Loads and deserializes the embedded text object metadata blob.
pub fn load_text_object_metadata() -> TextObjectsBlob {
	load_blob(TEXT_OBJECTS_BLOB, "text_objects")
}

/// Loads and deserializes the embedded option metadata blob.
pub fn load_option_metadata() -> OptionsBlob {
	load_blob(OPTIONS_BLOB, "options")
}

/// Loads and deserializes the embedded gutter metadata blob.
pub fn load_gutter_metadata() -> GuttersBlob {
	load_blob(GUTTERS_BLOB, "gutters")
}

/// Loads and deserializes the embedded statusline metadata blob.
pub fn load_statusline_metadata() -> StatuslineBlob {
	load_blob(STATUSLINE_BLOB, "statusline")
}

/// Loads and deserializes the embedded hook metadata blob.
pub fn load_hook_metadata() -> HooksBlob {
	load_blob(HOOKS_BLOB, "hooks")
}

/// Loads and deserializes the embedded notification metadata blob.
pub fn load_notification_metadata() -> NotificationsBlob {
	load_blob(NOTIFICATIONS_BLOB, "notifications")
}

/// Loads and deserializes the embedded theme metadata blob.
pub fn load_theme_metadata() -> ThemesBlob {
	load_blob(THEMES_BLOB, "themes")
}
