//!
//! Handlers are registered explicitly during editor initialization.
//! The handler registries and [`dispatch_result`] function are generated by
//! `#[derive(DispatchResult)]` on [`ActionResult`].
//!
//! The [`result_handler!`](crate::actions::result_handler) macro is defined in
//! [`crate::actions::macros`] for consistency with other registration macros.
//!
//! Extension handlers should use [`result_extension_handler!`](crate::actions::result_extension_handler)
//! and are dispatched after the core per-variant handlers.
//!
//! [`ActionResult`]: crate::actions::ActionResult
//! [`dispatch_result`]: crate::actions::dispatch_result

use crate::actions::{ActionResult, Capability};

/// Outcome of handling an action result.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HandleOutcome {
	/// Result was handled, continue running.
	Handled,
	/// Result was handled, editor should quit.
	Quit,
	/// This handler explicitly declined the result (try next handler in slice).
	NotHandled,
}

/// A handler for a specific ActionResult variant.
#[derive(Clone)]
pub struct ResultHandler {
	/// Name for debugging/logging.
	pub name: &'static str,
	/// Priority (lower runs first, default 0).
	pub priority: i16,
	/// Capabilities required for this handler.
	pub required_caps: &'static [Capability],
	/// Handle the result, returning the outcome.
	pub handle: fn(&ActionResult, &mut super::EditorContext, bool) -> HandleOutcome,
}

impl std::fmt::Debug for ResultHandler {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		f.debug_struct("ResultHandler")
			.field("name", &self.name)
			.field("priority", &self.priority)
			.field("required_caps", &self.required_caps)
			.finish()
	}
}
